### ISSUE TITLE
DB構成を検討する

### ISSUE THREAD

**Issue by KazukiNakamura26** [KazukiNakamura26/welldone-api#3]
# 概要
firebaseのcloud firestoreのDB構成を検討する。

# 実現したい機能
* ユーザーが参照したい情報
- 自分の名前
- 自分が所属するproject
- 自分が送ったメッセージ
- 自分が受け取ったメッセージ

* メッセージが持つべき情報
- 自分のID
- 誰が書いたか
- 内容
- 誰が受け取ったか

* プロジェクトが持つべき情報
- ID
- 自分の名前

# 実装者へ
* DB構成について十分に検討いただき、このIssueのツリーに結果を記載してほしい。
また下記URLにおいてER図の作成を行っていただきたい。
https://app.cacoo.com/o/OFuylINXv0

**Comment by tm-t-fujii** [comment]
ER図作成しました。

**Comment by KazukiNakamura26** [comment]
DB構成ありがとうございました。
こちらを基に作成致します。
